source 'https://rubygems.org'

# Distribute your app as a gem
# gemspec

# Server requirements
# gem 'thin' # or mongrel
# gem 'trinidad', :platform => 'jruby'

# Project requirements
gem 'rake'
gem 'puma'

# components to test

gem 'memcached'
# Component requirements
# gem 'erb'

# Optional json codecs
# gem 'yajl-ruby', :platform => 'mri'  # smaller memory footprint
# gem 'oj'                             # faster

# Test requirements

# Padrino Stable Gem

# Or Padrino Edge
gem 'padrino', :git => 'git://github.com/padrino/padrino-framework.git'

# Or Individual Gems
# %w(core gen helpers cache mailer admin).each do |g|
#   gem 'padrino-' + g, '0.10.7'
# end
